version: 0.1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-1:392453725290:task-definition/small-forest:7"
        LoadBalancerInfo:
          ContainerName: "app"
          ContainerPort: 3000
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets: ["subnet-09dbe9f1bf007ae72", "subnet-0e798d1b25210738e"]
            SecurityGroups: ["sg-020166ea8edbad284"]
            AssignPublicIp: "ENABLED"
        PlatformVersion: "LATEST"
