import type { NextPage } from "next";
import Head from "next/head";
import { Container, Flex, Box, VStack } from "@chakra-ui/react";
import { TwitterTimelineEmbed } from "react-twitter-embed";

import { useDeviceCondition } from "~/hooks/device_condition";

import { ConditionStat } from "~/components/ConditionStat";
import { Title } from "~/components/Title";

const Home: NextPage = () => {
  const { now, loading, mutate, revalidating } = useDeviceCondition();
  return (
    <Flex
      flexDir="column"
      alignItems="center"
      h="100vh"
      overflowY="auto"
      py={8}
    >
      <Head>
        <title>Welcome Smafore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex pb={6}>
        <Title />
      </Flex>
      <Container
        maxW="container.sm"
        display="flex"
        flexDir="column"
        justifyContent="center"
        alignItems="center"
      >
        <VStack
          flexDir="column"
          justifyContent="center"
          alignItems="center"
          w="full"
          px={2}
          spacing={4}
          maxW={{ base: "full", md: "xs" }}
        >
          <ConditionStat
            condition={now}
            mutate={mutate}
            loading={loading}
            revalidating={revalidating}
          />
          <Container maxW="sm" minH="300px" maxH="520px" h="full" px={0}>
            <Flex
              rounded="md"
              shadow="xs"
              w="full"
              h="full"
              sx={{
                ">div": {
                  w: "full",
                  overflowY: "auto",
                },
              }}
            >
              <TwitterTimelineEmbed
                onLoad={function noRefCheck() {}}
                screenName="Met_Komori"
                options={{
                  height: "520px",
                }}
                sourceType="profile"
              />
            </Flex>
          </Container>
        </VStack>
      </Container>
    </Flex>
  );
};

export default Home;
